# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC3001SignUP2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC3001SignUP2(self):
    self.driver.get("https://dev-np.netryde.com/")
    self.driver.set_window_size(1218, 727)
    self.driver.find_element(By.ID, "Sign upTextArea").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_user-menu-link_1tnn4_70:nth-child(1) > svg").click()
    time.sleep(3)
    # self.driver.switch_to.frame(0)

    # self.driver.find_element(By.ID, "checkbox").click()
    # time.sleep(15)
    # self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "1").click()
    self.driver.find_element(By.ID, "1").send_keys("bibgxjhj@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "3").click()
    self.driver.find_element(By.ID, "3").click()
    self.driver.find_element(By.ID, "3").send_keys("M!k3th3fr34k")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    self.driver.find_element(By.ID, "4").click()
    self.driver.find_element(By.ID, "4").send_keys("M!k3th3fr34k")

    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[@id=\'root\']/div/div/div[2]/div[2]/div[2]/button").click()
    time.sleep(30)
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "A verification link has been sent to your email"
  
